title: "Pedram's blog"
description: "A blog about programming and stuff"
baseurl: ""
url: "https://pdrum.github.io"

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-redirect-from

sass:
  custom: "/_sass/custom/solarized.scss"

collections:
  courses:
    output: true
    permalink: /courses/:path/
